USE [master]
GO
/****** Object:  Database [TrainsDiploma]    Script Date: 08.06.2023 14:17:15 ******/
CREATE DATABASE [TrainsDiploma]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TrainsDiploma', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\TrainsDiploma.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'TrainsDiploma_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\TrainsDiploma_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [TrainsDiploma] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TrainsDiploma].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [TrainsDiploma] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [TrainsDiploma] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [TrainsDiploma] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [TrainsDiploma] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [TrainsDiploma] SET ARITHABORT OFF 
GO
ALTER DATABASE [TrainsDiploma] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [TrainsDiploma] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [TrainsDiploma] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [TrainsDiploma] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [TrainsDiploma] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [TrainsDiploma] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [TrainsDiploma] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [TrainsDiploma] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [TrainsDiploma] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [TrainsDiploma] SET  ENABLE_BROKER 
GO
ALTER DATABASE [TrainsDiploma] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [TrainsDiploma] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [TrainsDiploma] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [TrainsDiploma] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [TrainsDiploma] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [TrainsDiploma] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [TrainsDiploma] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [TrainsDiploma] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [TrainsDiploma] SET  MULTI_USER 
GO
ALTER DATABASE [TrainsDiploma] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [TrainsDiploma] SET DB_CHAINING OFF 
GO
ALTER DATABASE [TrainsDiploma] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [TrainsDiploma] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [TrainsDiploma] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [TrainsDiploma] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [TrainsDiploma] SET QUERY_STORE = OFF
GO
USE [TrainsDiploma]
GO
/****** Object:  Table [dbo].[OnlineKassa]    Script Date: 08.06.2023 14:17:23 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[OnlineKassa](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nchar](100) NOT NULL,
	[PaymentTypeId] [int] NOT NULL,
 CONSTRAINT [PK_OnlineKassa] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PaymentType]    Script Date: 08.06.2023 14:17:24 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PaymentType](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nchar](100) NOT NULL,
 CONSTRAINT [PK_PaymentType] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Role]    Script Date: 08.06.2023 14:17:24 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Role](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nchar](20) NOT NULL,
	[IsWorker] [bit] NOT NULL,
	[IsAdmin] [bit] NOT NULL,
 CONSTRAINT [PK_Role] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Route]    Script Date: 08.06.2023 14:17:24 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Route](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[DepartureTime] [datetime] NOT NULL,
	[DepartureCity] [nchar](100) NOT NULL,
	[DurationInMinutes] [int] NOT NULL,
	[ArrivalCity] [nchar](100) NOT NULL,
 CONSTRAINT [PK_Route] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Ticket]    Script Date: 08.06.2023 14:17:24 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Ticket](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[BuyTime] [datetime] NOT NULL,
	[Price] [int] NOT NULL,
	[RouteId] [int] NOT NULL,
 CONSTRAINT [PK_Ticket] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Transaction]    Script Date: 08.06.2023 14:17:24 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Transaction](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[UserId] [int] NOT NULL,
	[Value] [float] NOT NULL,
	[IsComplited] [bit] NOT NULL,
	[PaymentType] [datetime] NOT NULL,
	[KassaId] [int] NOT NULL,
 CONSTRAINT [PK_Transaction] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[User]    Script Date: 08.06.2023 14:17:24 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[User](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Login] [nchar](50) NOT NULL,
	[Token] [ntext] NULL,
	[Balance] [float] NOT NULL,
	[RoleId] [int] NOT NULL,
 CONSTRAINT [PK_User] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[UserToTicket]    Script Date: 08.06.2023 14:17:24 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[UserToTicket](
	[UserId] [int] NOT NULL,
	[TicketId] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Transaction] ADD  CONSTRAINT [DF_Transaction_IsComplited]  DEFAULT ((0)) FOR [IsComplited]
GO
ALTER TABLE [dbo].[User] ADD  CONSTRAINT [DF_User_Balance]  DEFAULT ((0)) FOR [Balance]
GO
ALTER TABLE [dbo].[OnlineKassa]  WITH CHECK ADD  CONSTRAINT [FK_OnlineKassa_PaymentType] FOREIGN KEY([PaymentTypeId])
REFERENCES [dbo].[PaymentType] ([Id])
GO
ALTER TABLE [dbo].[OnlineKassa] CHECK CONSTRAINT [FK_OnlineKassa_PaymentType]
GO
ALTER TABLE [dbo].[Ticket]  WITH CHECK ADD  CONSTRAINT [FK_Ticket_Route] FOREIGN KEY([RouteId])
REFERENCES [dbo].[Route] ([Id])
GO
ALTER TABLE [dbo].[Ticket] CHECK CONSTRAINT [FK_Ticket_Route]
GO
ALTER TABLE [dbo].[Transaction]  WITH CHECK ADD  CONSTRAINT [FK_Transaction_OnlineKassa] FOREIGN KEY([KassaId])
REFERENCES [dbo].[OnlineKassa] ([Id])
GO
ALTER TABLE [dbo].[Transaction] CHECK CONSTRAINT [FK_Transaction_OnlineKassa]
GO
ALTER TABLE [dbo].[Transaction]  WITH CHECK ADD  CONSTRAINT [FK_Transaction_User] FOREIGN KEY([UserId])
REFERENCES [dbo].[User] ([Id])
GO
ALTER TABLE [dbo].[Transaction] CHECK CONSTRAINT [FK_Transaction_User]
GO
ALTER TABLE [dbo].[User]  WITH CHECK ADD  CONSTRAINT [FK_User_Role] FOREIGN KEY([RoleId])
REFERENCES [dbo].[Role] ([Id])
GO
ALTER TABLE [dbo].[User] CHECK CONSTRAINT [FK_User_Role]
GO
ALTER TABLE [dbo].[UserToTicket]  WITH CHECK ADD  CONSTRAINT [FK_UserToTicket_Ticket] FOREIGN KEY([TicketId])
REFERENCES [dbo].[Ticket] ([Id])
GO
ALTER TABLE [dbo].[UserToTicket] CHECK CONSTRAINT [FK_UserToTicket_Ticket]
GO
ALTER TABLE [dbo].[UserToTicket]  WITH CHECK ADD  CONSTRAINT [FK_UserToTicket_User] FOREIGN KEY([UserId])
REFERENCES [dbo].[User] ([Id])
GO
ALTER TABLE [dbo].[UserToTicket] CHECK CONSTRAINT [FK_UserToTicket_User]
GO
USE [master]
GO
ALTER DATABASE [TrainsDiploma] SET  READ_WRITE 
GO
